[package]
name = "card_reveal_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.5", default-features = false, features = ['std'] }
sha2 = { version = "0.10", default-features = false }
